version: "3"

services:
#  extra_hosts: # will work only with docker-compose 1.3+
#    - "probot.local:127.0.0.1"
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'probot-webserver-postgres'
    restart: unless-stopped
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    networks:
      - postgresql
  postgresql:
    build: ./bin/postgresql
    container_name: 'probot-postgresql'
    restart: unless-stopped
    ports:
      - "${HOST_MACHINE_POSTGRESQL_PORT:-5432}:5432"
    volumes: 
      - ${POSTGRESQL_DATA_DIR-./data/postgresql}:/var/lib/postgresql
      - ${POSTGRESQL_LOG_DIR-./logs/postgresql}:/var/log/postgresql
      - ./db_init/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER:-docker}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:-docker}
      PGDATA: /data/postgres
    networks:
      - postgresql
  pgadmin:
    container_name: probot_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgresql
    restart: unless-stopped
  redis:
    container_name: 'probot-redis'
    image: redis:latest
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
networks:
  postgresql:
    driver: bridge
volumes:
  postgres:
  pgadmin:

